### ISSUE TITLE
New contributors or organization for this project

### ISSUE THREAD

**Issue by joubertredrat** [joubertredrat/Matomo-ProtectTrackID#16]
Hi guys,

Thanks for use this plugin, I'm glad that you like it. 

Since some years I'm very busy with my job and other things in my life, then isn't good that I continue as only manager for this project, I can help as I can, but is good to have others to manage this project too.

With this in mind, we have 2 solutions for this, I add other contributors with permission for manage project with me or create organization and transfer this project for that.

What you think guys? Let's discuss

**Comment by joubertredrat** [comment]
ping @KZeni @rolandinsh @saschanos from #15

**Comment by rolandinsh** [comment]
from https://github.com/joubertredrat/Piwik-ProtectTrackID/pull/15#issuecomment-769069869 : 
you can exclude me as a contributor as am not very familiar with @matomo-org ecosystem and development :|
If that will change in the future will create a pull request :)

**Comment by saschanos** [comment]
Sounds good to have other contributors for managing the project :). Maybe it would be a good idea to create a guideline what should be tested before merging something into master because there's no automatic tests for now?

**Comment by KZeni** [comment]
I have a few plugins in the directory and went through the Matomo 3 to 4 upgrade process. I could certainly lend a hand in this as a contributor (such as https://github.com/joubertredrat/Piwik-ProtectTrackID/pull/15 and following https://developer.matomo.org/guides/migrate-matomo-3-to-4 to get it available for Matomo 4 in the official plugin directory [it mentions not having it span multiple major versions, but that's what I did on the 5 plugins I have in the directory without issue & without needing to create a branch in GitHub... just increased the max version supported from 4.x to 5.x in plugin.json... though creating a branch for the different major Matomo versions wouldn't be the worst thing to do so we're following their official instructions to avoid issues later on while not abandoning those using Matomo 3.])

That all being said, I'm also busy with things so my contributions may be limited to a few things here & there, but it's better than nothing, I suppose.

**Comment by KZeni** [comment]
I noticed https://github.com/joubertredrat/Piwik-ProtectTrackID/pull/15 has been merged, but it still needs a new release to be created before the plugin shows up on https://plugins.matomo.org with the updated support.

Actually, if we want this plugin to retain Matomo 3 support while adding Matomo 4 support, it seems like we might want/need to:

1. Create a GitHub branch for Matomo 3 (leaving master to be used for version 4)
2. Confirm the GitHub service set up for the plugin directory is working (across both branches)
3. Revert the changes in https://github.com/joubertredrat/Piwik-ProtectTrackID/pull/15 back to what they were before on that Matomo 3 branch
4. Update the plugin info & changelog on the v3 branch
5. Create a new release on the v3 branch
6. Keep these updates on the v4 branch
7. Update the plugin info & changelog on the v4 branch (make to be a version release newer than the v3 branch [probably x.1 versions newer] so they don't collide in Matomo's plugin directory setup [it looks directly at plugin.json and needs the version to be different even if they're in different branches on GitHub and have different Matomo version requirements. Updates to the Matomo v3 plugin, if needed & unlikely, can then use x.x.1 version increments to never bump into the Matomo 4 plugin, with that being an x.1 increment over Matomo 3's plugin version, while being patched as needed.])
8. Create a new release on the v4 branch
9. Confirm https://plugins.matomo.org/ProtectTrackID (currently only accessible via https://plugins.matomo.org/ProtectTrackID?matomoversion=3 due to not having a version for modern Matomo) shows Matomo 3 & 4 are supported with their corresponding download options shown & working accordingly (a-la https://plugins.matomo.org/TwitterFeedWidgetByAmperage)

**Comment by KZeni** [comment]
Maybe that wouldn't be too difficult/involved for you, @joubertredrat, without needing to rope me in before its done (I could still be added as a contributor for later updates if/when needed). I'll await an update either way.

When it comes to adding contributors vs putting this in an organization that people are added to, I think the fact that this is an isolated project with no plans (that I'm aware of) to make more would lead to just adding people to this one repo being the way to go. Creating an organization would just add unnecessary overhead from what I can tell.
