### ISSUE TITLE
fatal type error in Hasher

### ISSUE THREAD

**Issue by Oreolek** [joubertredrat/Matomo-ProtectTrackID#52]
PHP Fatal error: Uncaught TypeError: `Piwik\Plugins\ProtectTrackID\Hasher::decode()`: Return value must be of type int, null returned in `/plugins/ProtectTrackID/Hasher.php:44`

**Comment by joubertredrat** [comment]
Hi @Oreolek, could you provide more information about this error for our debug? For example: Matomo version, PHP version.

**Comment by Oreolek** [comment]
current stable, php8.2

**Comment by joubertredrat** [comment]
Hi @Oreolek. I made a test here using last Matomo 5 and plugin version, PHP 8.3.4 and I didn't see any errors here, tracking was working normally.

Are you having this issue in plugin configuration or during tracking? Is it possible to check if your server have PHP bcmath, gmp and mbstring extensions installed?

**Comment by joubertredrat** [comment]
I added unit tests for PHP since 7.3 to 8.2, as possible to see here. https://github.com/joubertredrat/Matomo-ProtectTrackID/pull/53

**Comment by Oreolek** [comment]
I didn't have `gmp` installed, yes.
But why is this relevant? Isn't it enough to edit one line in Hasher.php and force an int type instead of `NULL`?

```php
return (int) $this->hashids->decode($value)[0];
```

https://github.com/joubertredrat/Matomo-ProtectTrackID/blob/master/Hasher.php#L41

**Comment by joubertredrat** [comment]
@Oreolek you need to have  `bcmath` and `gmp` extensions installed for the lib used by plugin to be able to do arbitrary and multiple precision mathematics during encode or decode process.

I guess this is the reason you facing this issue.

About your suggestion for edit the [#L41](https://github.com/joubertredrat/Matomo-ProtectTrackID/blob/master/Hasher.php#L41), I will add validations and throw exceptions for prevent this, but the method already expect int as return type, then we need to understand the reason that in your case is trying to returning null instead of this.

**Comment by joubertredrat** [comment]
No response, then I'm assuming that was solved
